alter table FINANCE_HOT_FIX_REQUEST add constraint FK_FINANCE_HOT_FIX_REQUEST_ON_ACCED foreign key (ACCED_ID) references FINANCE_ASSET(ID);
create index IDX_FINANCE_HOT_FIX_REQUEST_ON_ACCED on FINANCE_HOT_FIX_REQUEST (ACCED_ID);
