alter table FINANCE_ISSUE_FILE add constraint FK_FINANCE_ISSUE_FILE_ON_DOCUMENT foreign key (DOCUMENT_ID) references SYS_FILE(ID);
alter table FINANCE_ISSUE_FILE add constraint FK_FINANCE_ISSUE_FILE_ON_ISSUE foreign key (ISSUE_ID) references FINANCE_ISSUE(ID);
create index IDX_FINANCE_ISSUE_FILE_ON_DOCUMENT on FINANCE_ISSUE_FILE (DOCUMENT_ID);
create index IDX_FINANCE_ISSUE_FILE_ON_ISSUE on FINANCE_ISSUE_FILE (ISSUE_ID);
