alter table FINANCE_HOT_FIX_REQUEST add constraint FK_FINANCE_HOT_FIX_REQUEST_ON_ASSET foreign key (ASSET_ID) references FINANCE_ASSET(ID);
create index IDX_FINANCE_HOT_FIX_REQUEST_ON_ASSET on FINANCE_HOT_FIX_REQUEST (ASSET_ID);
