alter table FINANCE_HOT_FIX_REQUEST add constraint FK_FINANCE_HOT_FIX_REQUEST_ON_ISSUE foreign key (ISSUE_ID) references FINANCE_ISSUE(ID);
alter table FINANCE_HOT_FIX_REQUEST add constraint FK_FINANCE_HOT_FIX_REQUEST_ON_COMPANY foreign key (COMPANY_ID) references FINANCE_COMPANY(ID);
alter table FINANCE_HOT_FIX_REQUEST add constraint FK_FINANCE_HOT_FIX_REQUEST_ON_BUSINESS foreign key (BUSINESS_ID) references FINANCE_BUSINESS(ID);
alter table FINANCE_HOT_FIX_REQUEST add constraint FK_FINANCE_HOT_FIX_REQUEST_ON_EXECUTOR foreign key (EXECUTOR_ID) references SEC_USER(ID);
create index IDX_FINANCE_HOT_FIX_REQUEST_ON_ISSUE on FINANCE_HOT_FIX_REQUEST (ISSUE_ID);
create index IDX_FINANCE_HOT_FIX_REQUEST_ON_COMPANY on FINANCE_HOT_FIX_REQUEST (COMPANY_ID);
create index IDX_FINANCE_HOT_FIX_REQUEST_ON_BUSINESS on FINANCE_HOT_FIX_REQUEST (BUSINESS_ID);
create index IDX_FINANCE_HOT_FIX_REQUEST_ON_EXECUTOR on FINANCE_HOT_FIX_REQUEST (EXECUTOR_ID);
