alter table FINANCE_PROJECT add constraint FK_FINANCE_PROJECT_ON_MANAGER foreign key (MANAGER_ID) references SEC_USER(ID);
create index IDX_FINANCE_PROJECT_ON_MANAGER on FINANCE_PROJECT (MANAGER_ID);
