alter table FINANCE_PROJECT add constraint FK_FINANCE_PROJECT_ON_PARENT foreign key (PARENT_ID) references FINANCE_PROJECT(ID);
create index IDX_FINANCE_PROJECT_ON_PARENT on FINANCE_PROJECT (PARENT_ID);
