alter table FINANCE_ASSET add constraint FK_FINANCE_ASSET_ON_RESPONSIBLE_IT foreign key (RESPONSIBLE_IT) references SEC_USER(ID);
create index IDX_FINANCE_ASSET_ON_RESPONSIBLE_IT on FINANCE_ASSET (RESPONSIBLE_IT);
